# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: pn-db:1.0 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/psql/data
        # Health checks (pg_isready)
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
          initialDelaySeconds: 3 # start_period in Docker Compose
          periodSeconds: 3 # interval
          timeoutSeconds: 7 # timeout
          failureThreshold: 10 # retries
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
          initialDelaySeconds: 5 # Give it more time before checking liveness
          periodSeconds: 3
          timeoutSeconds: 7
          failureThreshold: 20
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-data-pvc