# db-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: default 

spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage that for this nodes application  must be enough