# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque  
data:
  POSTGRES_USER: bHVjYXM= # base64 encoded 'lucas'
  POSTGRES_PASSWORD: MTIzNA== # base64 encoded '1234'
  POSTGRES_DB: cG5fZGF0YWJhc2U= # base64 encoded 'pn_database'