services:

  web:
    container_name: web_pn
    build: 
      context: ./web 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - pn-net

  db:
    container_name: db_pn
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pn_database
    networks:
      - pn-net
  
networks:
  pn-net:
    driver: bridge
