services:
  web:
    container_name: web_pn
    build: 
      context: ./web 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - pn-net
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "app.py"]

  db:
    container_name: db_pn
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pn_database
    networks:
      - pn-net
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U lucas -d pn_database"] 
      interval: 5s 
      timeout: 5s 
      retries: 5 
      start_period: 10s 

networks:
  pn-net:
    driver: bridge
