# haproxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 80 # Port on the HAProxy container
      nodePort: 30080 # Optional: Specify a NodePort if you want a fixed port (range 30000-32767)
  type: NodePort # Expose externally via Minikube IP and NodePort