FROM opensuse/leap:latest

RUN zypper --non-interactive update && \
    zypper --non-interactive install -y python3 python3-pip 

WORKDIR /app

COPY app /app

RUN pip3 install Flask

EXPOSE 5000

CMD ["python3", "/app/app.py"]
