FROM opensuse/leap:15.5

RUN zypper --non-interactive update && \
    zypper --non-interactive install -y python3 python3-pip python3-psycopg2


WORKDIR /app

COPY ./app /app

RUN pip3 install Flask

EXPOSE 5000
RUN ls -l /usr/bin/python3
CMD ["python3", "/app/app.py"]
