FROM opensuse/leap:latest

RUN zypper --non-interactive update && \
    zypper --non-interactive install -y python3 python3-pip postgresql-devel

WORKDIR /app

COPY app /app

RUN pip3 install -r /app/requirement.txt

EXPOSE 5000

CMD ["python3", "app/app.py"]
